server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xiadadasystemadmin?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
#  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: com.zls.zzz.entity
  #用于mybatis在控制台打印sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

