spring:
  profiles:
    active: dev

  thymeleaf:
    view-names: /*
    cache: false
    prefix: /WEB-INF/html
logging:
    level:
      com.example.demo.mapper: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
